Media pages, home 2col
mrengy/vanguard-history pull request #132
Opened 2023-02-25 19:36 UTC by shekharkhedekar

Sorry for the delay! This PR should take care of:
https://3.basecamp.com/5067876/buckets/22032865/todos/5779549376
https://3.basecamp.com/5067876/buckets/22032865/todos/5779552291
https://3.basecamp.com/5067876/buckets/22032865/todos/5804419723
https://3.basecamp.com/5067876/buckets/22032865/todos/5819623418

2023-02-25 21:29 UTC, mrengy requested changes
Nice work! No worries. I appreciate you doing this during / shortly after your vacation. 

This resolves all of the Basecamp to-dos you linked, except I'm getting an error with the AJAX call on "show all media" on a single year story. It's successful when I checkout the main branch. Looks as though it's the ' + "1" ' on line 42 of buttons.js - removing that made it work for me. What are you trying to achieve with the ' + "1" '? Remove if it's not necessary?

2023-02-25 21:45 UTC, mrengy commented
@shekharkhedekar [screen recording](https://jumpshare.com/v/xrr28cvhoMFmqcwgSZMw) and screenshot of the error I got

<img width="1407" alt="Screen Shot 2023-02-25 at 4 12 32 PM" src="https://user-images.githubusercontent.com/2223603/221380951-4b62ad5b-a5a1-4c30-9431-5598bf0f10cd.png">

2023-02-25 22:27 UTC, shekharkhedekar commented
> Nice work! No worries. I appreciate you doing this during / shortly after your vacation.
> 
> This resolves all of the Basecamp to-dos you linked, except I'm getting an error with the AJAX call on "show all media" on a single year story. It's successful when I checkout the main branch. Looks as though it's the ' + "1" ' on line 42 of buttons.js - removing that made it work for me. What are you trying to achieve with the ' + "1" '? Remove if it's not necessary?

Debugging the error case! I’ll remove

2023-02-26 01:12 UTC, mrengy approved these changes

2023-02-26 01:12 UTC, merged